-- CHỈ THÊM những cột BẮT BUỘC cho Entity - Tối thiểu nhất

-- 1. Amenity entity cần icon
ALTER TABLE amenities 
ADD COLUMN IF NOT EXISTS icon VARCHAR(50);

-- 2. RoomImage entity cần các field này
ALTER TABLE room_images 
ADD COLUMN IF NOT EXISTS alt_text VARCHAR(200),
ADD COLUMN IF NOT EXISTS display_order INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS file_size BIGINT,
ADD COLUMN IF NOT EXISTS mime_type VARCHAR(100);

-- 3. RoomDetail entity cần các field này
ALTER TABLE room_details 
ADD COLUMN IF NOT EXISTS smoking_allowed BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS pet_friendly BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS wifi_speed VARCHAR(50),
ADD COLUMN IF NOT EXISTS air_conditioning BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS minibar BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS balcony BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS ocean_view BOOLEAN DEFAULT FALSE;

-- 4. Cập nhật status enum (BẮT BUỘC cho RoomStatus enum)
ALTER TABLE rooms MODIFY COLUMN status ENUM('AVAILABLE', 'BOOKED', 'MAINTENANCE') DEFAULT 'AVAILABLE';
